### ISSUE TITLE
Rework folio functions for API updates

### ISSUE THREAD

**Issue by kuhnrl30** [kuhnrl30/LendingClub#11]

**Comment by dcaud** [comment]
I can't see how `FolioBuy` can be useful until the data provided by Lending Club is improved. As is, it looks like `FolioListing` returns `markupordiscount` values that are wacky. For example, there are whole numbers like "9" which seem to actually correspond to 0.09.  I also can't seem to match results from FolioListing with what is available by browsing Folio's search results. That is, I filter based on outstanding principal (or another variable) and then can't find the LoanID.

Have you had success?

**Comment by kuhnrl30** [comment]
I definitely see the issue with the markupordiscount field.  That's coming from LC- the function is just downloading the data using the link at the bottom of the search results.  Nothing fancy there.

As for finding notes in the search results- I have to ask- did you uncheck the default search params to include late notes? The download doesn't filter anything but the site defaults to excluding any late notes.  If you were looking for a late note, it would be excluded from the results on the site.   

LC updated their folio API a few weeks back and I'm just about ready to release LendingClub v2.0 with new functions to match.  Hopefully much of this will be corrected with that release.  If you are willing, I'd love a beta tester before pushing to CRAN.  Install directly from github with: 

```
devtools::install_github("kuhnrl30/LendingClub", ref= "dev")
```

**Comment by dcaud** [comment]
Hi. A quick test of V2.0 showed no problems, but I didn't spend much time on it. I've also got too little cash to really test the Buy function. I'll keep trying to beta test it.

I think the following helps better parse the `markupordiscount` field, along with other fields (notice the col_type change):

```
FolioListing<- function(updatedSince=NULL){
    

      r<- GET(searchURL, 
              query=list('updatedSince' = updatedSince),
              add_headers("Authorization"= LC_CRED[[2]],
                          "Accept" = "text/csv"))

      parsed<- content(r,
                       as="parsed",
                       # type = "text/csv",
                       encoding ='UTF-8', #,UTF-8
                       col_types= "iiddcdddiciiTTlciddic") #iinncnnniciiTTccinnic #ccccccccccccccccccccc
      
      structure(
        list(content = parsed,
             response = r),
        class = c("folio_api","LendingClub_api"))
    }
```

**Comment by dcaud** [comment]
A V2 bug?

`FolioOrders(orderType = "BUY")` returns values that don't make sense to me.

For example,

creditScoreTrend values are all "FLAT"
ficoEndRangeLow are all -1
markupOrDiscount ranges wildly from -0.0074 to 1199

And in case I haven't mentioned this yet, excellent work with this package!!! These are minor bugs for great new features.
