### ISSUE TITLE
Enhancements to Dashboard

### ISSUE THREAD

**Issue by kuhnrl30** [kuhnrl30/LendingClub#17]
Update dashboard for tabset:  Current reporting to go in first tab, second tab to be a list of late notes by portfolio.  

- How much is outstanding?  
- Payback ratio?
- Last payment? 
- Days late?

Change distribution chart to show outstanding principle, not loan count.

**Comment by kuhnrl30** [comment]
Closed with https://github.com/kuhnrl30/LendingClub/commit/721c30caf573b0a56e8bb14efbb0a4df0d203347

**Comment by Predacity** [comment]
Hey Ryan, see the lendingclub email on apis? does that affect your api?

Ayed Al Sabawi, MBA, CFA, CIM

Mobile: +1 (603) 277-1510
Skype: ayed.alsabawi
ayedalsabawi@gmail.com
