### ISSUE TITLE
AccountSummary() Error

### ISSUE THREAD

**Issue by joshlkeller** [kuhnrl30/LendingClub#6]
Anyone else get this error?

```
> AccountSummary()
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 1, 0
```

Thanks!

**Comment by kuhnrl30** [comment]
The API can return JSON objects with NULL values but there wasn't anything to handle them when converting the response to a data frame.  I modified the internals to remove the null values which should prevent the error your seeing.   

Please download the latest version on GIthub to test the fix.  If it works for you then I'll push the update to CRAN.

**Comment by joshlkeller** [comment]
Thanks! It's working well now. Very much appreciated.
